using Egret.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Egret.Services
{
    public class BaseService
    {
        /// <summary>
        /// Returns the dbcontext as generated by dependency injection and passed to this base class.
        /// </summary>
        protected EgretContext Context { get; }

        public BaseService(EgretContext context)
        {
            Context = context;
        }

    }
}
