using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Egret.DataAccess;

namespace Egret.Controllers
{
    /// <summary>
    /// This controller is used as a base class for managing derived controllers, consistently setting up dbcontext access, and applying uniform authorization requirements.
    /// </summary>
    [Authorize]
    public abstract class ManagedController : Controller
    {
        public ManagedController(EgretContext context)
        {
            Context = context;
        }

        /// <summary>
        /// Returns the dbcontext as generated by dependency injection and passed to this base class.
        /// </summary>
        protected EgretContext Context { get; }
    }
}