using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Egret.DataAccess;

namespace Egret.Controllers
{
    [Authorize]
    public class ManagedController : Controller
    {
        private EgretContext _context;

        /// <summary>
        /// This controller is used as a base class for managing other controllers, consistently establishing a dbcontext, and applying uniform authorization requirements.
        /// </summary>
        /// <param name="context"></param>
        public ManagedController(EgretContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Returns the dbcontext as generated by dependency injection and passed to this class.
        /// </summary>
        protected EgretContext Context
        {
            get { return _context; }
        }
    }
}